Repository RetroAchievements/RAWeb, pull requests merged in 2025-04, with the labels that each got.

#3388 feat(emulators): add supports_toolkit field and ticket creation warning
  app/Filament/Resources/EmulatorResource.php
  app/Models/Emulator.php
  app/Platform/Data/EmulatorData.php
  database/migrations/2025_04_03_000000_update_emulators_table.php
  lang/en_US.json
  resources/js/features/achievements/components/CreateAchievementTicketMainRoot/CreateAchievementTicketForm/EmulatorCoreField.tsx
  resources/js/features/achievements/components/CreateAchievementTicketMainRoot/CreateAchievementTicketForm/EmulatorSelectField.test.tsx
  resources/js/features/achievements/components/CreateAchievementTicketMainRoot/CreateAchievementTicketForm/EmulatorSelectField.tsx
  resources/js/test/factories/createEmulator.ts
  resources/js/types/generated.d.ts
Labels: deployment/sql

#3404 Support compatibility flag for game hashes
  app/Connect/Actions/BuildClientPatchDataAction.php
  app/Connect/Actions/CreateWarningAchievementAction.php
  app/Connect/Actions/IdentifyGameHashAction.php
  app/Connect/Actions/InjectPatchClientSupportLevelDataAction.php
  app/Enums/GameHashCompatibility.php
  app/Filament/Resources/GameResource/Pages/Hashes.php
  app/Helpers/database/game.php
  app/Helpers/database/hash.php
  app/Models/Game.php
  app/Models/GameHash.php
  app/Platform/Controllers/GameHashController.php
  app/Platform/Data/GameHashData.php
  app/Platform/Data/GameHashesPagePropsData.php
  database/factories/GameHashFactory.php
  lang/en_US.json
  public/API/API_GetGameHashes.php
  public/dorequest.php
  resources/js/features/games/components/HashesMainRoot/HashesList/HashesList.test.tsx
  resources/js/features/games/components/HashesMainRoot/HashesList/HashesList.tsx
  resources/js/features/games/components/HashesMainRoot/HashesMainRoot.test.tsx
  resources/js/features/games/components/HashesMainRoot/HashesMainRoot.tsx
  resources/js/features/games/components/HashesMainRoot/OtherHashesSection.test.tsx
  resources/js/features/games/components/HashesMainRoot/OtherHashesSection.tsx
  resources/js/types/generated.d.ts
  tests/Feature/Api/V1/GameHashesTest.php
  tests/Feature/Api/V1/GameListTest.php
  tests/Feature/Connect/GameIdTest.php
  tests/Feature/Connect/PatchDataTest.php
  tests/Feature/Connect/StartSessionTest.php
  tests/Feature/Connect/SubmitGameTitleTest.php
  tests/Feature/Connect/UnlocksTest.php
  tests/TestCase.php
Labels: deployment/sql

#3156 feat(api): Add sortOrder to API_GetComments
  app/Models/Comment.php
  public/API/API_GetComments.php
  tests/Feature/Api/V1/CommentsTest.php
Labels: status/needs-docs

#3416 feat(multiset): add image_asset_path column on achievement_sets table
  app/Models/AchievementSet.php
  app/Models/Game.php
  app/Platform/Actions/SyncAchievementSetImageAssetPathFromGameAction.php
  app/Platform/AppServiceProvider.php
  app/Platform/Commands/SyncAchievementSetImageAssetPaths.php
  database/migrations/2025_04_14_000000_update_achievement_sets_table.php
Labels: deployment/command

#3430 add conversion for Find the Pixel 2025 event
  app/Platform/Commands/SyncEvents.php
Labels: deployment/command
